version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-graphql
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mongodb-graphql
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: